version: 1.0.{build}
skip_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore ".\src\GameOfLife.sln"
build:
  verbosity: minimal